{
 "title": "Муравская",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Ощущаемая температура",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Ощущаемая температура",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "Balcony/Outdoor_feeling_temperature"
      }
     ]
    }
   ]
  },
  {
   "title": "Погода на улице",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Уличные ощущения",
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_s" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony/Outdoor_feeling" }
     ]
    }
   ]
  },
  {
   "title": "Температура воздуха",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Улица",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "OutdoorTemperature/state" }
     ]
    }
   ]
  },
  {
   "title": "Относительная влажность",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Outdoor_balcony/humidity" }
     ]
    }
   ]
  },
  {
   "title": "Атмосферное давление",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\")/1.333 FROM \"mqtt_data\" WHERE (\"client\"::tag = 'zigbee' AND \"channel\"::tag = 'Server_room_sensor/pressure') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Server_room_sensor/pressure" }
     ]
    }
   ]
  },
  {
   "title": "UV index",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\") / 2.5\nFROM \"mqtt_data\"\nWHERE\n  (\"client\"::tag = 'wb_AMTXYWW3'\n   AND \"channel\"::tag = 'Meshtastic/uv_lux_smoothed')\n  AND $timeFilter\n  AND \"value_f\" >= 0\n  AND \"value_f\" <= 37.5\nGROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2.5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Meshtastic/uv_lux_smoothed" }
     ]
    }
   ]
  },
  {
   "title": "Радиационный фон",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "μR/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\")/2 FROM \"mqtt_data\" WHERE (\"client\"::tag = 'zigbee' AND \"channel\"::tag = 'Radiation_sensor/radiation_dose_per_hour') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "Radiation_sensor/radiation_dose_per_hour"
      }
     ]
    }
   ]
  },
  {
   "title": "Доступность Интернета",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_Home" }
     ]
    }
   ]
  },
  {
   "title": "Индекс ультрафиолета",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "UV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\") / 2.5\nFROM \"mqtt_data\"\nWHERE\n  (\"client\"::tag = 'wb_AMTXYWW3'\n   AND \"channel\"::tag = 'Meshtastic/uv_lux_smoothed')\n  AND $timeFilter\n  AND \"value_f\" >= 0\n  AND \"value_f\" <= 37.5\nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2.5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Meshtastic/uv_lux_smoothed" }
     ]
    }
   ]
  },
  {
   "title": "Давление воды в стояках, Атм",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "Холодная",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "WC_water_pressure/bar_1" }
     ]
    },
    {
     "alias": "Горячая",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "WC_water_pressure/bar_2" }
     ]
    }
   ]
  },
  {
   "title": "Теплоноситель, °C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Отопление",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "Igor_heating_temperature/temperature"
      }
     ]
    },
    {
     "alias": "Стояк горячей воды",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "WC_hot_water_temperature/temperature"
      }
     ]
    }
   ]
  },
  {
   "title": "Атмосферное давление, mmHg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "Атмосферное давление",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\")/1.333 FROM \"mqtt_data\" WHERE (\"client\"::tag = 'zigbee' AND \"channel\"::tag = 'Server_room_sensor/pressure') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Server_room_sensor/pressure" }
     ]
    }
   ]
  },
  {
   "title": "Температура воздуха, °C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Среднесуточная",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony/Avg_temperature" }
     ]
    },
    {
     "alias": "Текущая",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "OutdoorTemperature/state" }
     ]
    },
    {
     "alias": "Точка росы",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony/Dewpoint" }
     ]
    }
   ]
  },
  {
   "title": "Радиационный фон, μR/h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "Радиационный фон",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\")/2 FROM \"mqtt_data\" WHERE (\"client\"::tag = 'zigbee' AND \"channel\"::tag = 'Radiation_sensor/radiation_dose_per_hour') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "Radiation_sensor/radiation_dose_per_hour"
      }
     ]
    }
   ]
  },
  {
   "title": "Абсолютная влажность, g/m³",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "Абсолютная влажность",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony/Abs_humidity" }
     ]
    }
   ]
  },
  {
   "title": "Относительная влажность, %H",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "alias": "Относительная влажность",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Outdoor_balcony/humidity" }
     ]
    }
   ]
  },
  {
   "title": "Освещенность, lux",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "Освещенность",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony-ms/Illuminance" }
     ]
    }
   ]
  },
  {
   "title": "Частота сети, Hz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "alias": "Частота",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "e-meter/Frequency" }
     ]
    }
   ]
  },
  {
   "title": "ICMP RTT Мир Митино Телеком, ms",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "ММТ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_MMT" }
     ]
    },
    {
     "alias": "CloudFlare DNS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_DNS_CloudFlare" }
     ]
    },
    {
     "alias": "Yandex",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_Yandex" }
     ]
    },
    {
     "alias": "Google DNS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_DNS_Google" }
     ]
    },
    {
     "alias": "Youtube",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_Youtube" }
     ]
    },
    {
     "alias": "WhatsApp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_WhatsApp" }
     ]
    },
    {
     "alias": "Telegram",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_Telegram" }
     ]
    }
   ]
  },
  {
   "title": "ICMP RTT МегаФон, ms",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "alias": "Yandex",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "mf/RTT_Yandex" }
     ]
    },
    {
     "alias": "CloudFlare DNS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "mf/RTT_DNS_CloudFlare" }
     ]
    },
    {
     "alias": "Google DNS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "mf/RTT_DNS_Google" }
     ]
    },
    {
     "alias": "Youtube",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "mf/RTT_Youtube" }
     ]
    },
    {
     "alias": "WhatsApp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "mf/RTT_WhatsApp" }
     ]
    },
    {
     "alias": "Telegram",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "mf/RTT_Telegram" }
     ]
    }
   ]
  },
  {
   "title": "Напряжение сети, V",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "e-meter/Urms" }
     ]
    }
   ]
  }
 ]
}