services:
  mosquitto:
    image: eclipse-mosquitto:2.0.22
    restart: unless-stopped
    container_name: mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/passwd:/mosquitto/config/passwd
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - /etc/letsencrypt/live/dansu.ru/fullchain.pem:/mosquitto/certs/fullchain.pem
      - /etc/letsencrypt/live/dansu.ru/privkey.pem:/mosquitto/certs/privkey.pem
    ports:
      - "0.0.0.0:1883:1883"
      - "0.0.0.0:8883:8883"
    labels:
      com.centurylinklabs.watchtower.enable: "${WATCHTOWER_LABEL}"

  influxdb:
    image: influxdb:1.8.10
    restart: unless-stopped
    container_name: influxdb
    volumes:
      - influxdb-data:/root
      - ./secrets:/run/secrets
      - ./influxdb/init-scripts:/docker-entrypoint-initdb.d
      - ./influxdb/backup:/backup
      - ./influxdb/etc:/etc/influxdb
    ports:
      - "0.0.0.0:8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_TOKEN}
      - INFLUXDB_COORDINATOR_MAX_SELECT_POINT=100
      - INFLUXDB_HTTP_MAX_ROW_LIMIT=100000
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_DB=mqtt_data
        #    labels:
        #      com.centurylinklabs.watchtower.enable: "${WATCHTOWER_LABEL}"
    mem_limit: 500m
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8086/ping"]
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 20s

  mqtt2influx:
    image: iot-stack-mqtt2influx:local
    restart: unless-stopped
    container_name: mqtt2influx

    depends_on:
      influxdb:
        condition: service_started
      mosquitto:
        condition: service_started

    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      MQTT_TOPIC: "#"
      INFLUX_HOST: influxdb
      INFLUX_PORT: "8086"
      INFLUX_DATABASE: mqtt_data
      INFLUX_USERNAME: mqtt2influx_wr
      INFLUX_PASSWORD_FILE: /run/secrets/influx_mqtt2influx_password
      INFLUX_TIMEOUT: "5"
      INFLUX_RETRY_INITIAL: "1"
      INFLUX_RETRY_MAX: "30"
      MQTT_USERNAME_FILE: /run/secrets/mqtt2influx_username
      MQTT_PASSWORD_FILE: /run/secrets/mqtt2influx_password
      TZ: Europe/Moscow

    secrets:
      - mqtt2influx_username
      - mqtt2influx_password
      - influx_mqtt2influx_password

    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "3"

  grafana:
    image: grafana/grafana:12.3.0-19020365962
#    user: root
    restart: unless-stopped
    container_name: grafana
    depends_on:
      influxdb: { condition: service_started }
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/provisioning/dashboards/json:/var/lib/grafana/dashboards/json:ro
      - grafana-storage:/var/lib/grafana
      - ./grafana/custom.ini:/etc/grafana/custom.ini
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://dansu.ru
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LIVE_ENABLED=false
#    labels:
#      com.centurylinklabs.watchtower.enable: "${WATCHTOWER_LABEL}"
    expose: ["3000"]

  nginx:
    image: nginx:1.29-alpine
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "127.0.0.1:8080:8080"
    depends_on: [grafana]
#    labels:
#      com.centurylinklabs.watchtower.enable: "${WATCHTOWER_LABEL}"

  telegraf:
    image: telegraf:1.36.3-alpine
    restart: unless-stopped
    user: telegraf:991
    depends_on:
      influxdb: { condition: service_started }
      mosquitto: { condition: service_started }
    container_name: telegraf
    network_mode: host
    pid: host
    userns_mode: host
    environment:
      - HOST_PROC=/proc
      - MQTT_PW=${MQTT_PW}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  mosquitto-data:
  mosquitto-log:
  influxdb-data:
  kapacitor-data:
  grafana-storage:

secrets:
  mqtt2influx_username:
    file: ./secrets/mqtt2influx_username

  mqtt2influx_password:
    file: ./secrets/mqtt2influx_password

  influx_mqtt2influx_password:
    file: ./secrets/influx_mqtt2influx_password
