{
 "title": "Муравская",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Температура воздуха",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Улица",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "OutdoorTemperature/state" }
     ]
    }
   ]
  },
  {
   "title": "Относительная влажность",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Outdoor_balcony/humidity" }
     ]
    }
   ]
  },
  {
   "title": "Атмосферное давление",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\")/1.333 FROM \"mqtt_data\" WHERE (\"client\"::tag = 'zigbee' AND \"channel\"::tag = 'Server_room_sensor/pressure') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Server_room_sensor/pressure" }
     ]
    }
   ]
  },
  {
   "title": "Радиационный фон",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "μR/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\")/2 FROM \"mqtt_data\" WHERE (\"client\"::tag = 'zigbee' AND \"channel\"::tag = 'Radiation_sensor/radiation_dose_per_hour') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "Radiation_sensor/radiation_dose_per_hour"
      }
     ]
    }
   ]
  },
  {
   "title": "Доступность Интернета",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_Home" }
     ]
    }
   ]
  },
  {
   "title": "Теплоноситель",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Отопление",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "Igor_heating_temperature/temperature"
      }
     ]
    },
    {
     "alias": "Стояк",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "WC_hot_water_temperature/temperature"
      }
     ]
    }
   ]
  },
  {
   "title": "Температура воздуха",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Среднесуточная",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony/Avg_temperature" }
     ]
    },
    {
     "alias": "Текущая",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "OutdoorTemperature/state" }
     ]
    },
    {
     "alias": "Точка росы",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony/Dewpoint" }
     ]
    }
   ]
  },
  {
   "title": "Радиационный фон, мкР/ч",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\")/2 FROM \"mqtt_data\" WHERE (\"client\"::tag = 'zigbee' AND \"channel\"::tag = 'Radiation_sensor/radiation_dose_per_hour') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      {
       "condition": "AND",
       "key": "channel::tag",
       "operator": "=",
       "value": "Radiation_sensor/radiation_dose_per_hour"
      }
     ]
    }
   ]
  },
  {
   "title": "Атмосферное давление",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "query": "SELECT mean(\"value_f\")/1.333 FROM \"mqtt_data\" WHERE (\"client\"::tag = 'zigbee' AND \"channel\"::tag = 'Server_room_sensor/pressure') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Server_room_sensor/pressure" }
     ]
    }
   ]
  },
  {
   "title": "Освещенность",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony-ms/Illuminance" }
     ]
    }
   ]
  },
  {
   "title": "Абсолютная влажность",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Balcony/Abs_humidity" }
     ]
    }
   ]
  },
  {
   "title": "Относительная влажность",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "zigbee" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "Outdoor_balcony/humidity" }
     ]
    }
   ]
  },
  {
   "title": "Напряжение сети",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "e-meter/Urms" }
     ]
    }
   ]
  },
  {
   "title": "Частота сети",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "e-meter/Frequency" }
     ]
    }
   ]
  },
  {
   "title": "ICMP RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "ММТ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_MMT" }
     ]
    },
    {
     "alias": "CloudFlare DNS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_DNS_CloudFlare" }
     ]
    },
    {
     "alias": "Yandex",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_Yandex" }
     ]
    },
    {
     "alias": "Google DNS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_DNS_Google" }
     ]
    },
    {
     "alias": "Youtube",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_Youtube" }
     ]
    },
    {
     "alias": "Telegram",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_data",
     "select": [
      [
       { "params": [ "value_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "client::tag", "operator": "=", "value": "wb_AMTXYWW3" },
      { "condition": "AND", "key": "channel::tag", "operator": "=", "value": "pi/RTT_Telegram" }
     ]
    }
   ]
  }
 ]
}