hostname = "kapacitor"
data_dir = "/var/lib/kapacitor"
default-retention-policy = "autogen"

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  pprof-enabled = false

[logging]
  file = "STDOUT"
  level = "INFO"

[load]
  enabled = true
  dir = "/etc/kapacitor/load"

[storage]
  boltdb = "/var/lib/kapacitor/kapacitor.db"

[fluxtask]
  enabled = false

[[influxdb]]
  enabled = true
  default = true
  name = "influxv1"
  urls = ["http://influxdb:8086"]

  username = "kapacitor_ro"
  password = ""

  timeout = "0s"
  startup-timeout = "30s"

  disable-subscriptions = true
  subscription-mode = "server"
  subscription-protocol = "http"

[reporting]
  enabled = false

[stats]
  enabled = false
