apiVersion: 1

datasources:
  - name: influxdb
    uid: ff0df601o8w00b
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: grafana_ro
    basicAuth: false
    isDefault: true
    editable: false
    jsonData:
      dbName: mqtt_data
      httpMode: POST
      pdcInjected: false
    secureJsonData:
      password: $INFLUX_GRAFANA_PASSWORD
