server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name dansu.ru;

    ssl_certificate     /etc/letsencrypt/live/dansu.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dansu.ru/privkey.pem;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    location = /api/live/ws { return 404; }

    location = / {
        return 301 /d/ad8btw2/muravskaja?orgId=1&from=now-7d&to=now&timezone=browser&refresh=15m;
    }

    location / {
        proxy_pass       http://grafana:3000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
    }
}
